In [2]:
import numpy as np

# desired array [
# [1,  6, 11],
# [2,  7, 12],
# [3,  8, 13],
# [4,  9, 14],
# [5, 10, 15]
# ]

In [7]:
a1 = np.arange(1,16).reshape(3,5).transpose()
print(a1)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [ ]:
a2 = np.arange(1,16).reshape(5,3)

In [ ]:
print(a2)

In [ ]:
a2.transpose()

In [ ]:
a2.reshape(5,3)

In [ ]:
a2.transpose((1,0))

In [ ]:
a2.transpose((1,0))

In [ ]:
a2.reshape(5,3)

In [ ]:
a2.reshape(3,5)

In [ ]:
a2.transpose()

In [9]:
# newaxis function
# TODO: find another, shorter way
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])

# x1+x2

In [10]:
x1_new = x1[:, np.newaxis]

In [11]:
print(x1_new)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [12]:
x1_new + x2 

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])