# NumPy demos

In [1]:
import numpy as np
import sys

## ndarray creation methods

Reference: https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

In [2]:
ndarr1 = np.array([1,2,3,4])
ndarr1

array([1, 2, 3, 4])

In [3]:
type(ndarr1)

numpy.ndarray

In [8]:
# using Python's range() function:
ndarr2 = np.array(range(1,11))
ndarr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
type(ndarr2)

numpy.ndarray

In [12]:
# using the numpy arange() method:
ndarr3 = np.arange(1,11)
ndarr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## ndarray attributes

Reference: https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#array-attributes

In [18]:
ndarr1x10 = np.arange(1, 11)
ndarr1x10.shape

(10,)

In [15]:
ndarr3x2 = np.array([[1,2], [3,4], [5,6]])

In [16]:
ndarr3x2.shape

(3, 2)

In [20]:
ndarr3x2 = np.arange(1,7, dtype="int32")
ndarr3x2.shape

(6,)

In [21]:
np.reshape(ndarr3x2, (2,3))

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

## Element wise operations

In [29]:
a1 = np.arange(1,4)
a2 = np.arange(4,7)
print(f'a1: {a1}')
print(f'a2: {a2}')

a1: [1 2 3]
a2: [4 5 6]


In [31]:
a1+a2

array([5, 7, 9])

## Indexing && Slicing

In [42]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
# a[i,j] where i are row indexes and j are col indexes
a[1,2]

6

In [52]:
# a[stat:stop-1:step]
a[0:3:2]

array([[1, 2, 3],
       [7, 8, 9]])

In [55]:
# a[i,j]
a[1:3,0:3:2]

array([[4, 6],
       [7, 9]])

In [54]:
a[1:3,[0,2]]

array([[4, 6],
       [7, 9]])