# NumPy ndarray object

An array object that represents a **multidimensional**, **homogeneous** array of **fixed-size** items

## Create Methods

Reference: https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

In [2]:
import numpy as np

### Create N dimensional arrays:

By literal - note that the number of opening squares equals the dimension

In [3]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

Create array filled with random values: __np.empty__ of type __np.int8__

In [4]:
b = np.empty( (3,2), dtype=np.int8  )
b

array([[-120, -117],
       [ -21,  114],
       [  19,  127]], dtype=int8)

Create array by __np.arange()__ method (quite simmilar to python's __range()__)

In [5]:
# np.arange(start, stop-1 ,step)
a1 = np.arange(1, 11,1) # start=0 and step = 1 are defaults, so can be omitted
print(f'a1: {a1}')

a2 = np.arange(10)
print(f'a2: {a2}')

a3 = np.arange(1,11,2)
print(f'a3: {a3}')

a1: [ 1  2  3  4  5  6  7  8  9 10]
a2: [0 1 2 3 4 5 6 7 8 9]
a3: [1 3 5 7 9]


## Basic Properties:

### shape - tuple of array dimensions

In [6]:
a1 = np.array([[1,2,3],[4,5,6]])
print(a1)
a1.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [7]:
a2 = np.arange(10)
print(a2)
a2.shape

[0 1 2 3 4 5 6 7 8 9]


(10,)

Note that the tuple (10, ) should be read as containg only one element, i.e - the number 10

### ndim - number of array dimensions

In [8]:
print(a1.ndim)
print(a2.ndim)

2
1


### dtype - data-type of the array’s elements

In [9]:
a1.dtype

dtype('int64')

### size - number of elements in the array

In [10]:
a1.size

6

### itemsize - length of one array element in bytes.

In [11]:
a1.itemsize

8

### nbytes - total bytes consumed by the elements of the array

In [12]:
a1.nbytes

48

### Memory comparison between Python's list and ndarray

In [13]:
l = list(range(100))
a = np.arange(100,dtype="int8")

# using the Python sys.getsizeof() method:
import sys
print(sys.getsizeof(l))
print(sys.getsizeof(a))

# using the nbytes ndarray atribute
print(a.nbytes)

856
204
100


## Arrays Algebra (Element Wise)

In [14]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

print("The result of a+2 is:")
print(a+2)
print("The result of a+b is:")
print(a+b)

The result of a+2 is:
[[3 4 5]
 [6 7 8]]
The result of a+b is:
[[ 2  4  6]
 [ 8 10 12]]


### matrix product: __dot()__ product

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Matrix_multiplication_qtl1.svg/930px-Matrix_multiplication_qtl1.svg.png" style="width:50%">

In [16]:
a = np.array([
	[1, 2, 3],
	[4, 5, 6]
])
b = np.array([
	[1,2],
	[3,4],
	[5,6]
])

# print(1*1+2*3+3*5)
# print(1*2+2*4+3*6)

a.dot(b)

22
28


array([[22, 28],
       [49, 64]])

In [21]:
b.dot(a)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

#### Comparison operators

In [ ]:
# compare array with single value:
a = np.array([1,2,3])
print(a<2)

# compare array with array (with same shape):
b = np.array([4,5,1])
print(a < b)


## Indexing and slicing

### One-dimensional Array Indexing

**Syntax**: array[n]

n >= 0 => get n+1 element, from left to right

n <= -1 => get n element, from right to left 

In [ ]:
a1 = np.arange(1,10)
print(a1)

print("\npositive index - from left to right - a1[1]")
print(a1[1])

print("\nnegative index - from right to left - a1[-1]")
print(a1[-1])

print("\nget elements with indexes 0 upto 3 (excluded) - a1[0:3]")
print(a1[0:3])

print("\nget all elements - a1[:]")
print(a1[:])

print("\nget all elements, without the last one - a1[:-1]")
print(a1[:-1])

print("\nslicing with step - a1[0:9:2]")
print(a1[0:9:2])

print("\nslicing with step - backwards - a1[-1::-2]")
print(a1[-1::-2])

### Multi dimensional arrays indexing


**syntax**

matrix[i,j]

i - index rows

j - index columns

In [ ]:
# let's have the array:
a1 = np.arange(1,10).reshape(3,3)
print(a1)

In [ ]:
# get an element with tuple index
a1[1,2]

In [ ]:
# get an element with indx chaining index - DO NOT USE THAT!
a1[1][2]

**Note: index chaining returns the same result, but is more inefficient as a new temporary array is created after the first index that is subsequently indexed by 2.**

### Slicing

One-dim arrays - Syntax

arr[start:stop:step]

start = index of start element. Default = beginning of array.

stop -1 = index of last element. Default = end of array (inclusive)

step   = the step to increment indexes on slice. Optional. Default 1.

In [ ]:
a1 = np.arange(1,10)
print(a1)

print( list(a1[0:2:1]) )

# all defaults - returns a copy
print( list(a1[::]) )
print( list(a1[:]) )

# stop default - untill the end of array, inclusive
print( list(a1[2::]) )


Multi-dim arrays slicing

Syntax:

matrix[slice_row, slice_col]

In [ ]:
m = np.arange(1,10).reshape(3,3)
print(m)

print("\nSlice the first row - m[0,:]")
print(m[0,:])

print("\nSlice the first column - m[:,0]")
print(m[:,0])

print("\nSlice first 2 rows and columns - m[0:2, 0:2]")
print(m[0:2, 0:2])

print("\nSlice the corner elements - m[0::2, 0::2]")
m[0::2, 0::2]

### Boolean indexing

We can select certain values from a numpy array, if we mask it with a Boolean array (True/False values) with the **same shape**

In [ ]:
# this is the original array:
a = np.arange(1,6)
print(a)

# this is the mask:
mask = [True, True, False, True, False]

# lets apply the mask:
print(a[mask])

#### Masking example 1 : select only the even values

In [ ]:
# let's have a bigger array:
a = np.arange(1,20)

# and get only even numbers from it:
a[a%2==0]

How it works:

a%2 is calculated for each element of the array.

If result value, which serves as index, is True => the element is selected, 
if it is False the element is not selected 

#### Masking example 2 : map list elements to array of indexes

In [ ]:
# let's have a numpy array of repeated values 0, 1 or 2:
indexes = np.array([0, 2, 1, 2, 0, 1,2])

# and a list of colors:
colors = ['red', 'green', 'blue']

# let's group the elements of the 'indexes' array by color, according to 
# their values, which will be used as indexes in colors list
# For simplicity, we'll just print the groups, but if we need, we can save them in dictionary
for i in range(len(colors)):  
    print(f"{colors[i]} group:")
    print(indexes[indexes==i])
    

#### Masking example 3 : group 'scores' by category

Let's have an array of 'scores', and for each score we'll have to assign a category from a predefined list. So, we'll add to each score element the index of the category list.
The goal is to group scores by category.

In [ ]:
scores = np.array([
    [4, 1],
    [2, 0],
    [3, 0],
    [5, 1],
    [6, 1]
])

categories = ['good','bad']


for i in range(len(categories)):  
    # make the mask:
    mask = scores[:,1] == i
    print(mask)
    
    # now apply it to scores:
    print(f"\n{categories[i]} scores are:")
    print(scores[mask,0])

## Array Manipulations

#### Flatten the array

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel()

#### reshaping arrays: __np.reshape()__

In [ ]:
a = np.arange(1,10)
a

In [ ]:
a.reshape(3,3)

In [ ]:
a.reshape(1,9)