# Numpy Intro

In [9]:
import numpy as 


## Speed Test

In [10]:
SIZE = 2_000_000

# Create Python's lists
l1 = list(range(SIZE))
l2 = list(range(SIZE))

# Create Numpy Arrays

In [11]:
a1=np.arange(SIZE)
a2=np.arange(SIZE)

In [12]:
def python_lists():
    result = [(x+y) for x,y in zip(l1,l2)]
    print(result[0:10])

    
def numpy_arrays():
    result = a1 + a2
    print(result[0:10])

In [13]:
%time python_lists()
print('-'*50)
%time numpy_arrays()

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
CPU times: user 200 ms, sys: 23.9 ms, total: 224 ms
Wall time: 227 ms
--------------------------------------------------
[ 0  2  4  6  8 10 12 14 16 18]
CPU times: user 5.77 ms, sys: 3.49 ms, total: 9.26 ms
Wall time: 11.6 ms


In [14]:
%%bash
ls -l

total 8
-rw-rw-r-- 1 nemsys nemsys    0 Oct 20 14:39 jupyter_examples
-rw-rw-r-- 1 nemsys nemsys 2923 Oct 20 15:28 numpy_intro.ipynb
-rw-rw-r-- 1 nemsys nemsys 2047 Oct 20 15:03 Untitled.ipynb


## Numpy create methods

In [15]:
# create 1 dim array from python list (1..10)

In [24]:
l = range(10)
print(l)

a1 = np.array(l, dtype="int8")
print(a1.dtype)

range(0, 10)
int8


In [19]:
a1.shape

(10,)

In [22]:
a2 = np.full((3,3), 1)
print(a2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### Numpy Array Slicing

In [25]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [32]:
print(a1[0:3:-1])

[]


In [33]:
a3 = a1.reshape((5,2))

In [34]:
a3.shape

(5, 2)

In [35]:
a3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]], dtype=int8)

In [38]:
a3[2,1]

5

### Crete matrix (10, 10) filled with 1 only in elements above main diagonal

In [41]:
# TODO: check docs better
m1 = np.tri(10, 10, -1)

In [42]:
m1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [43]:
mask = m1>0
mask

array([[False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [ True,  True, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]])