# Create DataFrame

In [1]:
import numpy as np
import pandas as pd

## From Numpy 2dim array 

In [9]:
m = np.arange(1,10).reshape(3,3)
print(m)
print(m.shape[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3


In [ ]:

# index = numbers, columns = alphabetical
lower_a_ascii = 97
df = pd.DataFrame(m, columns=list(map(chr, range(lower_a_ascii, lower_a_ascii+m.shape[1]))))
df

In [4]:
df.head(2)

a  b  c
0  1  2  3
1  4  5  6

In [5]:
df.tail(1)

a  b  c
2  7  8  9

### Create DF from CSV

In [6]:
authors_df = pd.read_csv("./authors.csv", sep=',')
authors_df.head(10)

author                                          authorUrl
0           Mike Pirnat                            http://mike.pirnat.com/
1           David Mertz  http://www.oreilly.com/programming/free/functi...
2       Muhammad Yasoob                             http://pythontips.com/
3  B. Miller & D. Ranum                        http://reputablejournal.com
4     Jeffrey Elkner...                          http://greenteapress.com/
5  B. Miller & D. Ranum                       http://reputablejournal.com/
6           Zed A. Shaw                  http://learnpythonthehardway.org/
7          Mark Pilgrim             http://getpython3.com/diveintopython3/
8          Mark Pilgrim             http://getpython3.com/diveintopython3/
9       Allen B. Downey                      http://www.greenteapress.com/

In [7]:
authors_df.columns

Index(['author', 'authorUrl'], dtype='object')

In [12]:
authors_df[]]

KeyError: "None of [Int64Index([0, 5], dtype='int64')] are in the [columns]"

## loc[]

In [ ]:
authors_10 = authors_df.loc[1:11,:]
authors_10

TASK: print rows which author name starts with 'D'

In [13]:
s = 'abc'
s.startswith('b')

False

In [17]:
mask = authors_df.author.str.startswith('D')

In [18]:
authors_df.loc[mask ,:]

author                                          authorUrl
1    David Mertz  http://www.oreilly.com/programming/free/functi...
17  Dave Kuhlman                      http://www.rexx.com/~dkuhlman
25  Doug Hellman                       http://www.doughellmann.com/
54   David Mertz                             http://gnosis.cx/TPiP/

In [13]:
authors_df.head(10)

author                                          authorUrl
0           Mike Pirnat                            http://mike.pirnat.com/
1           David Mertz  http://www.oreilly.com/programming/free/functi...
2       Muhammad Yasoob                             http://pythontips.com/
3  B. Miller & D. Ranum                        http://reputablejournal.com
4     Jeffrey Elkner...                          http://greenteapress.com/
5  B. Miller & D. Ranum                       http://reputablejournal.com/
6           Zed A. Shaw                  http://learnpythonthehardway.org/
7          Mark Pilgrim             http://getpython3.com/diveintopython3/
8          Mark Pilgrim             http://getpython3.com/diveintopython3/
9       Allen B. Downey                      http://www.greenteapress.com/

In [20]:
# author start with 

In [21]:
df = pd.DataFrame(m, columns=['a','b','c'])
df

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

TASK:  print only for which: 
column a and acolumn c have even numbers

In [22]:
# mask = (df.a%2==0) and (df.c%2==1) 
mask = (df.a%2==0) & (df.c%2==1)
# mask = np.logical_and(df.a%2==0, df.c%2==0)
mask

0    False
1    False
2    False
dtype: bool

In [23]:
# df.loc[row, columns]

In [19]:
df.loc[ mask, :]

a  b  c
1  4  5  6

In [35]:
# TODO: why not work
mask = ( authors_df.author.str.contains("free") )
print(mask)
authors_df.head(10)

0     False
1     False
2     False
3     False
4     False
      ...  
70    False
71    False
72    False
73    False
74    False
Name: author, Length: 75, dtype: bool


author                                          authorUrl
0           Mike Pirnat                            http://mike.pirnat.com/
1           David Mertz  http://www.oreilly.com/programming/free/functi...
2       Muhammad Yasoob                             http://pythontips.com/
3  B. Miller & D. Ranum                        http://reputablejournal.com
4     Jeffrey Elkner...                          http://greenteapress.com/
5  B. Miller & D. Ranum                       http://reputablejournal.com/
6           Zed A. Shaw                  http://learnpythonthehardway.org/
7          Mark Pilgrim             http://getpython3.com/diveintopython3/
8          Mark Pilgrim             http://getpython3.com/diveintopython3/
9       Allen B. Downey                      http://www.greenteapress.com/