In [2]:
import numpy as np
import pandas as pd

## Task: create Series object with numbers [1..5], indexed with latin alphabetical

In [10]:
s1 = pd.Series({
    'a': 1,
    'b': 2,
    'c': 3,
    'd': 4,
    'e': 5,
}, index=['a','c'])
s1

0   NaN
1   NaN
dtype: float64

In [24]:
l = list(range(1,6))
arr = np.array(range(1,6))
print(arr)

s2 = pd.Series(arr, copy=True)
arr[0] = 9
print(s2)

[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64


In [13]:
s1[-3:]

a    1
c    3
dtype: int64

In [30]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[arr%2==0] 

array([ 2,  4,  6,  8, 10])

In [35]:
s = pd.Series(arr)
s
s[s%2==0]

1     2
3     4
5     6
7     8
9    10
dtype: int64

In [43]:
ds = pd.Series([1,2,3,4,5], dtype='int8', index=["a","b","c","d","e"])
ds

a    1
b    2
c    3
d    4
e    5
dtype: int8

In [44]:
ds[ds==6]

Series([], dtype: int8)

In [45]:
ds.dtype

dtype('int8')

In [46]:
ds1 = pd.Series([1,3], index=["a","c"])
ds2 = pd.Series([2,3], index=["b","c"])
print(ds1)
print(ds2)

a    1
c    3
dtype: int64
b    2
c    3
dtype: int64


In [49]:
ds1+ds2


a    NaN
b    NaN
c    6.0
dtype: float64

In [50]:
print(type(3.14))

<class 'float'>


In [52]:
print(type(np.NaN))

<class 'float'>


In [72]:
ds1 = pd.Series([1,3], index=['a','b'])
ds1

a    1
b    3
dtype: int64

In [73]:
df = pd.DataFrame([ds1, ds1], index=['a','b'])
df

a  b
a  1  3
b  1  3

In [63]:
df = pd.DataFrame({
    'a':ds1,
    'b':ds1
})
df

a  b
0  1  1
1  3  3

In [64]:
df.columns

Index(['a', 'b'], dtype='object')